### ISSUE TITLE
settings.py search sequence unintuitive and fragile

### ISSUE THREAD

**Issue by daphtdazz** [pyeve/eve#1023]
My first time out with Eve I ran:

    from eve import Eve
    app = Eve()

And got the exception:

```
Traceback (most recent call last):
  File "/Users/daphtdazz/.virtualenvs/py3/lib/python3.5/site-packages/eve/flaskapp.py", line 272, in validate_domain_struct
    domain = self.config['DOMAIN']
KeyError: 'DOMAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daphtdazz/.virtualenvs/py3/lib/python3.5/site-packages/eve/flaskapp.py", line 140, in __init__
    self.validate_domain_struct()
  File "/Users/daphtdazz/.virtualenvs/py3/lib/python3.5/site-packages/eve/flaskapp.py", line 274, in validate_domain_struct
    raise ConfigException('DOMAIN dictionary missing or wrong.')
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.
```

This turned out to be because I had django also installed in that virtualenv, which has a `'settings.py'` file in one of its directories, which Eve was trying to use. So I had a look at how Eve finds the `'settings.py'` file, in [flaskapp.py](https://github.com/pyeve/eve/blob/master/eve/flaskapp.py#L229), and the logic seems to be:

1. If we were passed (either via environment, or the call to `Eve()`) an absolute path use that.
2. If we were passed a relative path, first look for it in the directory of the application (`sys.argv[0]`).
3. Then look for it recursively in each directory in sys.path.

This seems unintuitive and fragile to me. Unintuitive because I would expect it first to look in the current directory, but it doesn't at all, nor does it make sense to me to look in the application's directory, and it makes no sense to recurse through all the system paths. Fragile because any module installed that happens to have a settings.py file in it is going to conflict.

So I think there are the following sub-issues:

1. The exception thrown should be improved. Eve should at least say which settings.py it was using in the exception so that you immediately understand it's looking in the wrong file. 

2. [The docs](http://eve.readthedocs.io/en/latest/config.html) should be improved, currently they do say that it will look through `sys.path`, but they are I think at worst wrong and best confusing, for example they say:

    > Eve will give precedence to dictionary-based settings first, then it will try to locate a file 
    > passed in EVE_SETTINGS environmental variable (if set) and finally it will try to locate 
    > settings.py or a file with filename passed to settings flag in constructor.

    Whereas actually judging by the code [if an absolute path is passed in](https://github.com/pyeve/eve/blob/master/eve/flaskapp.py#L227) via keyword argument that is prioritised over the environment.

3. I think either the resolution order could be rethought, and I'd suggest:

    1. Use absolute path or dictionary passed in to `Eve()`
    2. Use environment (relative or absolute).
    3. Look in current directory.
    2. Deprecate looking in application directory.
    3. Deprecate looking in `sys.path[]`.

Obviously, these are just suggestions! I'll probably make a patch for 1 at least as it's not likely to be controversial, and the others can be discussed.

([This question](https://stackoverflow.com/questions/31396208/where-is-settings-py-supposed-to-be-with-eve/44204533) on stackoverflow suggests I'm not the only one who's done this.)

**Comment by bomb-on** [comment]
Since I am the one who updated this particular function (PR: #962), let me try to explain the reasons behind it...

> This turned out to be because I had django also installed in that virtualenv, which has a 'settings.py' file in one of its directories, which Eve was trying to use.

Makes absolute sense. It never occurred to me that someone might use Django and Flask (Eve) in a same project and keep everything in same folder. I never assumed that and never tested out handling of `settings.py` for that case.

> This seems unintuitive and fragile to me. Unintuitive because I would expect it first to look in the current directory, but it doesn't at all, nor does it make sense to me to look in the application's directory(...)

What are "current directory" and "application directory" in your case?

> (...)and it makes no sense to recurse through all the system paths.

This was done purely for my specific use case while running Eve tests (explained in #962). It was sort of "last effort" to locate settings in a case when all else fails. Especially because Eve test are run with "custom" settings file (https://github.com/pyeve/eve/blob/master/eve/tests/__init__.py#L66) and this can become extremely messy, depending on too many factors (OS, PYTHONPATH, project's folder structure, even IDE, etc). I honestly assumed that this will be the least used method to locate settings if you follow some simple rules in your Eve project.

> Fragile because any module installed that happens to have a settings.py file in it is going to conflict.

True. As said, this is because I never assumed that there will be another `settings.py` in the project.

---

However, although I have no idea about your project structure, I put some effort to figure out why is this happening.

**There is a bug** which you mentioned, it is happening in one use case only (explained below), but I believe that in the end, solution to your problem might be just setting the `EVE_SETTINGS` environmental variable or passing the file path to Eve's `settings` parameter.

Assume following folder structure:

```
oxxo@null:~/Sites/evetest <evetest> $ ls -lR
total 8
-rw-r--r--  1 oxxo  staff   98 May 30 12:30 app.py
drwxr-xr-x  4 oxxo  staff  136 May 30 12:28 django_project
drwxr-xr-x  5 oxxo  staff  170 May 30 12:28 eve_project

./django_project:
total 8
-rw-r--r--  1 oxxo  staff   0 May 30 12:28 __init__.py
-rw-r--r--  1 oxxo  staff  18 May 30 12:28 settings.py

./eve_project:
total 16
-rw-r--r--  1 oxxo  staff   0 May 30 12:28 __init__.py
-rw-r--r--  1 oxxo  staff  37 May 30 12:20 custom_settings_file.py
-rw-r--r--  1 oxxo  staff  30 May 30 12:20 settings.py
```

Content of `django_project/settings.py` is irrelevant.
Content of `eve_project/custom_settings_file.py` is `DOMAIN = {'custom_settings_file': {}}`.
Content of `eve_project/settings.py` is `DOMAIN = {'settings_file': {}}`.
Content of `app.py` is:

```
from eve import Eve
SETTINGS = {'DOMAIN': {'no_file_only_dictionary': {}}}

app = Eve()
app.run()
```

- Running `app.py` (from the same folder where `app.py` is located), in this kind of setup results with `eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.` because iterating `sys.path` will hit Django settings first just because it's alphabetically before Eve folder.

- Passing the `SETTINGS` dictionary (located in `app.py`) to `app = Eve(settings=SETTINGS)` will result in loading the same `SETTINGS` dictionary.

- Passing the custom file name to Eve constructor (like `app = Eve(settings='custom_settings_file.py')`) will result in loading `eve_project/custom_settings_file.py` file.

- Passing the absolute path to Eve (`app = Eve(settings='/Users/oxxo/Sites/evetest/eve_project/settings.py')`) will result in loading exactly that file.

- Setting environmental variable `EVE_SETTINGS=custom_settings_file.py` will result in loading `eve_project/custom_settings_file.py` file, **unless `settings` parameter in `Eve()` constructor is an absolute path**.

- Setting absolute path to environmental variable `EVE_SETTINGS=/Users/oxxo/Sites/evetest/eve_project/custom_settings_file.py` will result in loading that file, **unless `settings` parameter in `Eve()` constructor is an absolute path**.

- Renaming your folders to make Eve project alphabetically before Django project and running Eve just like `app = Eve()` will load Eve with `eve_project/settings.py` file (default functionality).

---

> The exception thrown should be improved. Eve should at least say which settings.py it was using in the exception so that you immediately understand it's looking in the wrong file.

Absolutely agree.

> The docs should be improved(...)

Couldn't agree more! :))) I wrote the paragraph you mentioned and since English is not my primary language it might be that I explained everything in a strange way. My apologies for that. Of course that every improvement is more than welcome!

> I think either the resolution order could be rethought(...)

As I just mentioned and since Eve is an open source project, everyone is welcome to contribute :) I might take a look at this problem myself and propose a fix, but if you (or anyone else) has a better idea how to solve this magical issue feel free to [join with your own contribution](http://python-eve.org/contributing.html)!!

**Comment by bomb-on** [comment]
Anyways, fixing this should be a pretty easy task, I think that we just have to make an "agreement" how to solve it... Which rules should Eve follow in locating settings and in which order... Maybe @nicolaiarocci has a suggestion regarding this? =)

**Comment by nicolaiarocci** [comment]
Hey folks, thanks for bringing this up. I myself have not been happy about current implementation. I think that the resolution order provided by @daphtdazz makes sense, docs improvement included. @bomb-on would that break your use case?

With this being said, I'd probably flag having both django and eve in the same virtualenv, and even in the same folder structure, an anti-pattern :-)

**Comment by bomb-on** [comment]
@nicolaiarocci My use case is probably very specific, as much as any other developer's working environment. The problem I faced was that I had pretty different environments while running Eve tests and while running my app which is using Eve. Allow me to try to explain a bit...

I am working on OS X 10.12.5 with Python 3.4.5, using [pyenv](https://github.com/pyenv/pyenv) latest version, all that in PyCharm IDE 2017.1.2.

For this testing purpose I added 3 `print()` statements [immediately after `load_config()`](https://github.com/pyeve/eve/blob/master/eve/flaskapp.py#L202):
```python
print(os.path.dirname(os.path.realpath(__file__)))
print(os.path.dirname(sys.argv[0]))
print(sys.path)
```

## Eve Tests
I clone Eve project and create a PyCharm project out of it. In my PyCharm's "Run/Debug Configuration", I add py.test config only which end up like [this](https://s21.postimg.org/qy1ybbjw7/Untitled.png). When I "run" or "debug" this kind of project, what PyCharm actually does is this:
```bash
# in case of "run":
/Users/oxxo/.pyenv/versions/eve/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_pytest_runner.py --path .
Testing started at 11:29 ...
Launching py.test with arguments . in /Users/oxxo/Sites/eve

# in case of "debug":
/Users/oxxo/.pyenv/versions/eve/bin/python /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 65397 --file /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_pytest_runner.py --path .
Testing started at 11:24 ...
pydev debugger: process 84492 is connecting

Connected to pydev debugger (build 171.4249.47)
Launching py.test with arguments . in /Users/oxxo/Sites/eve
```
Running Eve tests in this way from PyCharm prints out current values:
```python
'/Users/oxxo/Sites/eve/eve'  # os.path.dirname(os.path.realpath(__file__))
'/Applications/PyCharm.app/Contents/helpers/pycharm'  # os.path.dirname(sys.argv[0])
# sys.path
[
    '/Users/oxxo/Sites/eve',
    '/Applications/PyCharm.app/Contents/helpers/pycharm',
    '/Users/oxxo/Sites/eve/eve/tests',
    '/Applications/PyCharm.app/Contents/helpers/pydev',
    '/Users/oxxo/.pyenv/versions/3.4.5/envs/eve/src/al',
    '/Users/oxxo/Sites/eve',
    '/Applications/PyCharm.app/Contents/helpers/pycharm',
    '/Applications/PyCharm.app/Contents/helpers/pydev',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python34.zip',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/plat-darwin',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/lib-dynload',
    '/Users/oxxo/.pyenv/versions/eve/lib/python3.4/site-packages'
]
```
For comparison, running the same app from terminal, like `py.test .` (from the Eve root folder) results in this:
```python
'/Users/oxxo/Sites/eve/eve'  # os.path.dirname(os.path.realpath(__file__))
'/Users/oxxo/.pyenv/versions/eve/bin'  # os.path.dirname(sys.argv[0])
# sys.path
[
    '/Users/oxxo/Sites/eve',
    '/Users/oxxo/.pyenv/versions/3.4.5/envs/eve/bin',
    '/Users/oxxo/.pyenv/versions/3.4.5/envs/eve/src/al',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python34.zip',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/plat-darwin',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/lib-dynload',
    '/Users/oxxo/.pyenv/versions/3.4.5/envs/eve/lib/python3.4/site-packages'
]
```


## Own Application Using Eve
Folder structure ([same as in my previous comment](https://github.com/pyeve/eve/issues/1023#issuecomment-304878147)):
```bash
oxxo@null:~/Sites/evetest <evetest> $ ls -lR
total 8
-rw-r--r--  1 oxxo  staff   98 May 30 12:30 app.py
drwxr-xr-x  4 oxxo  staff  136 May 30 12:28 django_project
drwxr-xr-x  5 oxxo  staff  170 May 30 12:28 eve_project

./django_project:
total 8
-rw-r--r--  1 oxxo  staff   0 May 30 12:28 __init__.py
-rw-r--r--  1 oxxo  staff  18 May 30 12:28 settings.py

./eve_project:
total 16
-rw-r--r--  1 oxxo  staff   0 May 30 12:28 __init__.py
-rw-r--r--  1 oxxo  staff  37 May 30 12:20 custom_settings_file.py
-rw-r--r--  1 oxxo  staff  30 May 30 12:20 settings.py
```

Content of `app.py`:
```python
from eve import Eve
SETTINGS = {'DOMAIN': {'no_file_only_dictionary': {}}}

app = Eve()
app.run()
```

Creating my own application, installing Eve (latest version) in it, creating a PyCharm project with settings like [this](https://s2.postimg.org/4nbtak1h5/Untitled2.png) and running it from PyCharm will run my app like this:
```bash
# in case of "run":
/Users/oxxo/.pyenv/versions/evetest/bin/python /Users/oxxo/Sites/evetest/app.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

# in case of "debug":
/Users/oxxo/.pyenv/versions/evetest/bin/python /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 50086 --file /Users/oxxo/Sites/evetest/app.py
pydev debugger: process 86581 is connecting

Connected to pydev debugger (build 171.4249.47)
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
and resulting print statements will show following:
```python
'/Users/oxxo/.pyenv/versions/3.4.5/envs/evetest/lib/python3.4/site-packages/eve'  # os.path.dirname(os.path.realpath(__file__))
'/Users/oxxo/Sites/evetest'  # os.path.dirname(sys.argv[0])
# sys.path
[
    '/Users/oxxo/Sites/evetest',
    '/Applications/PyCharm.app/Contents/helpers/pydev',
    '/Users/oxxo/Sites/evetest',
    '/Applications/PyCharm.app/Contents/helpers/pydev',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python34.zip',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/plat-darwin',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/lib-dynload',
    '/Users/oxxo/.pyenv/versions/evetest/lib/python3.4/site-packages'
]
```
For comparison, running the same app from terminal, like `python app.py` (obviously from the folder where `app.py` is located and with activated virtual environment) results in this:
```python
'/Users/oxxo/.pyenv/versions/3.4.5/envs/evetest/lib/python3.4/site-packages/eve'  # os.path.dirname(os.path.realpath(__file__))
''  # os.path.dirname(sys.argv[0])
# sys.path
[
    '/Users/oxxo/Sites/evetest',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python34.zip',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/plat-darwin',
    '/Users/oxxo/.pyenv/versions/3.4.5/lib/python3.4/lib-dynload',
    '/Users/oxxo/.pyenv/versions/evetest/lib/python3.4/site-packages'
]
```

---

So, this is my "specific" use case and my working environments. I'd like to add that most of my environment is configured in more/less standard and "default" way - Python interpreters are installed with the help of Pyenv and Homebrew, PyCharm config uses mostly default options for running/debugging, I am not messing up with my system paths or Python path at all (relying on PyCharm to include necessary paths as you can see on my screenshots) and the most important, I am actually trying to run an application with installed Eve only (in my real app, not from this example), following Eve documentation, and not including any other framework which is using same naming convention to load appropriate settings.

I'd like to point out also that the "bug" mentioned is actually **not a bug** per se... This just might be an issue with terribly written documentation about this specific functionality (my mistake, I agree). It is not a bug because in my [previous comment](https://github.com/pyeve/eve/issues/1023#issuecomment-304878147) you can see that it happens **_only when you set both `EVE_SETTINGS` environmental variable along with passing absolute path in `settings` parameter in Eve() constructor_** - the thing which one **_should not_** do, just like one **_should not_** rely that Django and Eve will run together as a "same project" or whatever the case is... The "bug" can be "fixed" purely by rephrasing the section in documentation...

---

To be honest, I am still struggling with understanding the reasons behind @daphtdazz use-case and how exactly he runs both Django and Eve applications and what is his folder structure... Maybe even following [Flask Application Dispatching](http://flask.pocoo.org/docs/0.12/patterns/appdispatch/) suggestions might solve his problems...

Looking at the proposal:

> I think either the resolution order could be rethought, and I'd suggest:
>   i. Use absolute path or dictionary passed in to Eve()
>   ii. Use environment (relative or absolute).
>   iii. Look in current directory.
>   iv. Deprecate looking in application directory.
>   v. Deprecate looking in sys.path[].

I still don't understand the difference between "current" directory and "application" directory. I believe that deprecating mentioned functionality will put as back in old code before my "intervention" (assuming that "current" directory is Eve directory). This will result in breaking "my personal" use case, the one which is nothing crazy, but simply trying to run Eve tests or my own app with Eve included from PyCharm with default project configuration =)

---

Finally, let me point out that **I am not advocating that my code is _the best_**, to error is human! =) Of course that I am open for any suggestion/solution which would work for **all** use-cases. It would be really great from @daphtdazz to join this discussion and clarify some of the things mentioned here, so we can start working on solution all together, without breaking each-other's projects all over again ;)

Thanks for being patient with this! ;)

**Comment by daphtdazz** [comment]
Thanks everyone for your comments! Eve is a lucky project to have all of you interested and looking after it.

I would like:

- someone to check my [`config.rst` file](https://github.com/daphtdazz/eve/blob/bad-config-file-help/docs/config.rst) (see below for notes) and see if I got it right.
- to get agreement on whether it's ok to remove the `sys.path` search, which is the part I most care about. See below under **settings.py conflicts**

For context, I'm not using Eve more than just playing with it at the moment, so I don't have a really burning need to get this fixed, but I just thought it would be good to help and try and make sure people coming to it new don't get the wrong impression. So I don't mind if the config resolution system is not changed, but think it's worth having the discussion. 

If it ends up that some amount of my suggestions, or close to them, are accepted, I'll be happy to make a pull request. If something else, then it's probably best for someone else to.

Various further thoughts below.

### Proposed docs / clarity fixes

I've made a few changes in [my branch](https://github.com/daphtdazz/eve/tree/bad-config-file-help) which:

- try and improve the docs and also the code without actually changing any behaviour. In particular see [config.rst](https://github.com/daphtdazz/eve/blob/bad-config-file-help/docs/config.rst) where I have tried to write in English exactly the procedures used in the code.
- improve the text in the exceptions thrown when an error is hit loading the config.
- rationalize the lookup logic to make it clearer.

I haven't made a pull request yet because I think it would be good to tidy up at the same time, if we're going to.

### settings.py conflicts

I agree that having django and flask installed in the same environment is unusual and probably undesirable. However, django and flask are not the only packages that have settings.py files included. pymongo and jedi, for example, also do. And who knows what else might be in someone else's environment. So the problem is more than just one of django vs. flask.

It seems the main stumbling block is that @bomb-on 's use case relies on it (I think?). I feel sure that there would be a way he could work around it, but options might include taking a layered approach (see **Other lookup options** below), or restructuring his app to separate out the config from the code, which would seem sensible to me anyway. 

### current dir vs application dir

By "the current directory" I just mean the directory that the app is run from. You know, it's the one you can see by doing `pwd` in a shell, or calling [`os.getcwd()`](https://docs.python.org/3/library/os.html#os.getcwd) from within python. I just think it's more common to look there for custom settings files, and is particularly convenient when developing; IDEs like Pycharm generally let you set it to be something useful when running builds / tests. It's not really very useful in production, but then you probably would use an absolute path.
 
Besides having the settings file installed as part of the package seems like a bad solution to me; generally it's good to separate code and configuration, which makes your application much easier to move from one place to another and reuse.

### Other lookup options

Another lookup option that you might want to consider is to layer environment settings on top of application settings on top of default settings. That way you can always override settings in the environment, but can also provide application specific defaults. So you could have...

files:

    myapp/
        settings.py
        run.py

    /usr/local/etc/eve/myapp.py

env:

    EVE_SETTINGS=/usr/local/etc/eve/myapp.py
    
myapp/run.py:

    from myapp import settings
    app = Eve(settings=settings)  
   
This would use the defaults, then adds `myapp/settings.py` then `/usr/local/etc/eve/myapp.py` which it gets from the environment. If you pass the module in as I illustrate, that means you wouldn't have to do any lookup of settings files at all, which reduces the complexity.

**Comment by bomb-on** [comment]
@daphtdazz Thanks a lot for all the info! Some things are much more clear to me now =)

I checked your `config.rst` and I personally think that we are actually overcomplicating instead of simplifying things with current code...

I'd like first to try out the `os.getcwd()` approach, because (without trying it out) I think it might be the best solution to get rid of `sys.path` usage (which I agree is probably bad idea in the first place). It might be that in all my testing efforts to find settings I didn't try out `os.getcwd()` in all possible combinations and therefore I didn't go that way...

However, this probably won't work once again if you have another folder alphabetically before Eve folder with `settings.py` in it. I am aware that Django is not the only framework which is using the same file name as Eve does, so to fix this particular use-case, I'd recommend to explicitly say in docs that in this case do not rely on Eve's automagical settings discovery, but to use environmental variable, absolute path or different file name for settings.

About other lookup options... The "layered" approach might be a nice feature, but I'm not sure is this desirable at all, hopefully @nicolaiarocci will know more details about it. It might lead to even more confusion since you will be able to override same value in `DOMAIN` dict multiple times. Again, it could be solved by simply clarifying it in docs =)

Just a quick question about this "layered" approach... Which settings would you expect to load if you run Eve with just `app = Eve()`? Would this be the equivalent of your example (importing settings and passing it to Eve)?

**Comment by daphtdazz** [comment]
@bomb-on if you just did `app = Eve()` I would expect that to load the default settings (in `eve.default_settings` only, but if `EVE_SETTINGS` was set in the environment I would expect those environment settings to be imported and override the default settings. Not the equivalent of my example, where the application has specified some settings that it wants to use *as well*, but in a full layered approach these would also get overridden by any settings passed in the environment.

I think a layered approach is quite common for settings. For example, Mac OSX uses it by having /System/Library, /Library and ~/Library folders which allow the system to specify defaults in /System/Library, which can be overridden for all users in /Library, and for individual users in ~/Library. Also Sublime Text provides a file with general defaults and user defaults which override them, so I think a lot of people will be intuitively quite familiar with it.
