### ISSUE TITLE
embedded return null

### ISSUE THREAD

**Issue by duyhungp** [pyeve/eve#1064]
i have 2 collections:
```javascript
'actors': {
    'schema': {  
             'name': { 'type': 'string' } 
     }
},
'films': {
    'schema': {
        'actors': {  
             'type': 'objectid',
             'data_relation': { 
                   'resource': 'actors',  
                   'field': '_id',  
                   'embeddable': True 
             }
        },
        'title': { 'type': 'string'}
    }
}
```

in actors collection has one item:
_id: ObjectId("59ba0d96043a810c03fea0fd")
name: "John"

in films collection has one item
_id: ObjectId("59ba07fa043a810c03fea0fb")
title: "film 2"
actor: ObjectId("59ba0d96043a810c03fea0fd")

but when call:  http://127.0.0.1:5000/films?embedded={"actors":1}, at the field actors always return null
```javascript
"items": [  
        {
            "title": "film 2",
            "_etag": "e59fabb67bbc8dd675252000246e2ade527dfc6f",
            "_updated": "Thu, 01 Jan 1970 00:00:00 GMT",
            "_created": "Thu, 01 Jan 1970 00:00:00 GMT",
            "_id": "59ba07fa043a810c03fea0fb",
            "actors": null
        }
],
```
Please help, what wrong in that config ?. Thanks.

**Comment by Amedeo91** [comment]
You should try check if the objectId you stored in the actor field it is actually an ObjectId and not a string.

In general, I would suggest to expose a new field (creating an idex on it of course) as externalId for such operation.

Otherwise, you can refer to this #1033 which will allow you to understand what it is going on and why it is no working by using the embedded hook event.

Regards,
Amedeo
