### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ngharo** [pyeve/eve#1098]
The homepage says
```
from eve import Eve

app = Eve()
app.run()
```
and then
```
$ curl -i http://example.com/people
HTTP/1.1 200 OK
```
But no explanation of ``/people``.

How does ``/people`` exist from that example? How is the webserver started?

It's a practically useless example.  As a new user, I want to see a basic end-to-end example.  I am not familiar with Flask.  Should I be?  Is some type of configuration required before this example works? What is does the configuration look like? If I am not the intended user, the home page should tell me.

Where _are_ the docs?  The docs link in the home page take me right back to the exact same contents as the homepage.

Please take this as constructive criticism from the perspective of a new user.

**Comment by nicolaiarocci** [comment]
Hello, thanks for your feedback. The intent of that snippet is simply introduce the tool and show the newcomer how easy it is to launch a RESTful API with eve. The [Quickstart](http://python-eve.org/quickstart.html), which is linked, goes into explaining all that you mention. That kind of follows Flask's [homepage](http://flask.pocoo.org) example, althought I must admit that Flask is probably doing a better work at it since it follows with relevant documentation/download links.

Please feel free to submit a PR with all the improvements you would like to see to that and other documentation pages. I am more than willing to review it!
