### ISSUE TITLE
A where query with a regex that looks like an ObjectID crashes Eve.

### ISSUE THREAD

**Issue by cburchert** [pyeve/eve#1164]
To reproduce use any Eve API with enabled $regex operator. Set this in your config:
```
MONGO_QUERY_BLACKLIST = []
``` 

A regex that contains 24 hex characters will be converted to an ObjectID by Eve. This results in an error when the query is sent to mongo, as it expects a string for the regex.

The problem is generated by this line https://github.com/pyeve/eve/blob/6398aba5034ca1d2d7c065108e92365cc5fe00e4/eve/io/mongo/mongo.py#L269

This is in Mongo.find. The query spec that is sent to Mongo DB is passed through _mongotize. This function converts everything it can to a datetime or ObjectID. This also converts a regex that looks like an Object ID to an ObjectID, causing the crash.

_mongotize already loads the schema of the requested resource, so it should be rather easy to modify the function to only cast to ObjectIDs where it makes sense.

### Environment

* Python version: Tested on 3.6
* Eve version: Tested on Eve 0.7.4, but the code did not change so it should still happen with the current master.

**Comment by nicolaiarocci** [comment]
What happens when you set `query_objectid_as_string` for the resource?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/512968/41297070-9dacdeca-6e5e-11e8-8993-18cf2643f850.png">

**Comment by hermannsblum** [comment]
@nicolaiarocci The suggested solution very much limits the applicability, either you are able to filter with field contents or with object, _ids, but never with both.

In any case, queries should bot be able to crash the application.

Wouldn't it be possible to limit the object-id-casting to those fields that are defined as a relationship?

**Comment by nicolaiarocci** [comment]
Yes, it is possible. But there are a number of corner cases we'd need to address, making the code (unnecessarily?) more complex. 

In general, Eve assumes duck typing: if it looks like an `objectid`, then it is an objectid. There are several situations where this assumption is important in the context of `_mongotize`: versioning and default id fields, for example. In both cases, there is no explicit `objectid` schema definition as fields are either implicit or internal. Yet, it is important to properly cast those fields.

Another case is complex queries, like `?'id_list': {'$in': ['50656e4538345b39dd0414f0']}}`. Here, because of recursion in `_mongotize` we lose track of the queried field. Yes we could address that, but again a lot of added complexity (and take a performance hit).

The `query_objectid_as_string` is a compromise in usability, performance, and simplicity. It is good enough for most non-standard use cases. I am hesitant to add more complexity here. I have a local branch with some code that goes in your desired direction, and to be honest I am not extremely happy with it.

At this time, I would dub the current workaround (`query_objectid_as_string`) as 'good enough'.

**Comment by nicolaiarocci** [comment]
PS: As a reference, I pushed a branch with experimental changes to add support for the requested feature (see commit above). It solves some issues (id fields; versioning), but not the most subtle ones like complex queries.
