### ISSUE TITLE
Projection exclusion disabled

### ISSUE THREAD

**Issue by cchayden** [pyeve/eve#1187]
Mongo does not support mixed inclusions and exclusions, but eve eliminates all exclusions unconditionally.  If there are no inclusions, it should honor exclusions.
Exclusions are handled by listing all inclusions and eliminating the exclusions.  This does not well for embedded fields.

### Expected Behavior

The properties field is not returned from this query.
```python
curl -i http://eve-demo.herokuapp.com/region?projection={"features.properties": 0}
```

This is the case whether or not the schema has allow_unknown.  
### Actual Behavior

The projection is eliminated entirely.

### Bug Location
The problem is the code in eve/io/base.py  on line 449-452.
Suggestion: add the following.
```python
        values = set(fields.values())
        if 0 in values and len(values) > 1:
```
This will allow embedded exclusions if allow_unknown is True.

### Environment

* Python version: 3.5.1
* Eve version: 0.8 -- same behavior in master branch.

**Comment by huandzh** [comment]
hi, @cchayden 

In the last attempt to support mixed projection ( #1128 ) , projection on embedded fields had been broken. It should be my fault to overlook the use case you have mentioned.

However, to support mixed projection on embedded fields could be over complicated. To fix base on current solution is very likely to introduce other issues.

Maybe we need an additional option in the settings to switch the two behaviors:

1. support projection on embedded fields but not mixed projection (behavior before v0.8)
1. support mixed projection (client/server) but not projection on embedded fields (behavior after v0.8)

Any idea?

**Comment by cchayden** [comment]
Of the two choices, I prefer #1.  

My idea is that eve should allow me access to the range of things that mongo can do.  If it offers more, that's good.  It can offer more when it knows more (the schema).  That's great.  When it does not (allow_unknown if True) then it should not get in the way.
So my suggestion is if allow_unknown is True, then pass through the projection to mongo.  If you want to check that there is no mixed projections, fine, but mongo will do its own checking, so why bother?
The two-line fix that I suggested will fix the case I care about, but not everything.  It will
1) prevent mixed projections
2) allow include-only and exclude-only
It will thus allow exclude terms if allow_unknown is True, but not if it is False.

**Comment by nicolaiarocci** [comment]
@huandzh your feeback on @cchayden's comment above? Thanks!

**Comment by huandzh** [comment]
@cchayden @nicolaiarocci sorry for the late reply. I was too busy with works last month. And there will be an incoming business trip which will last 2 weeks. Thus, i am still not sure whether i can fix this in time. 

I agree with @cchayden on case when allow_unknown is True, and intend to support mix projection with already defined schema. If this is OK, I will try to post a w.i.p pull request later this week.

## some thoughts on why bother with mix projections:

The root of this issue comes from different demands between API user and API developer **when user has no full knowledge on schema**. 

Examples:

1. Developers may omit certain fields by default to save bandwidth by exclusive projection. While, users may limit fields fetched by inclusive projection.
1. Developers may hide certain fields for security concerns by inclusive projection. While, users may want to omit certain fields.

In both instances, no mix projections are used by users or developers by their own side alone. But they require eve to support mix projections.

With ideal design, users should be allowed to use either inclusive or exclusive projection without further information.
