### ISSUE TITLE
Error PATCH null value to field which type integer

### ISSUE THREAD

**Issue by masrayie** [pyeve/eve#1290]
Hi,
I want to ask how to define schema accept null value when patch ?

Here my schema :

`'Document_No' : {
		'type' : 'integer',
		'nullable' : True
	},
`
At the initial it has value, for example 4, but i want to set it to be null using patch metod and i got this error.

`{
    "_issues": {
        "Document_No": "must be of integer type"
    },
    "_status": "ERR"
}`

Is it my schema corret ? or i miss something ?
Please help.

Thank you !

### Environment

* Python version: 3.6
* Eve version: 0.9

**Comment by djanmamur** [comment]
@masrayie, could you please also provide the PATCH payload ?

**Comment by djanmamur** [comment]
`{
	"Document_No": null
}`
?

**Comment by masrayie** [comment]
@djanmamur thanks for your responds

i tried using postman, first i set the value like you mention above, second i set the value with None.
i was using form-data in postman.

thanks

**Comment by djanmamur** [comment]
@masrayie, I assume when using a form-data your **null** value becomes a string. Thus, instead of sending `{ "Document_No": null }` it actually sends `{ "Document_No": "null" }` where Eve cannot validate a string value as an integer, which makes sense. Can you try to send your payload in a `JSON(application/json)` form ?
![image](https://user-images.githubusercontent.com/16831129/60255748-9c098580-98d0-11e9-9fc0-0a2309a5077a.png)

**Comment by masrayie** [comment]
It works ! Thank you @djanmamur !
