### ISSUE TITLE
Eve crashes when gunicorn tries to run it - problem with loading config file

### ISSUE THREAD

**Issue by shea256** [pyeve/eve#137]
On line 154 of flaskapp.py, we have an invalid assumption:

`assume the path is relative to the calling script folder`

When you run something with gunicorn, sys.argv[0] refers to the path of the calling script, but this is quite different from the path of the Eve app.

In my case, it's
~/Users/username/.virtualenvs/virtualenv_name/bin/gunicorn
vs.
~/Users/username/code/app_name

**Comment by mloskot** [comment]
FYI, I had to apply the workaround from https://github.com/nicolaiarocci/eve/issues/137#issuecomment-25569408 in order to make a sample Eve app running on Azure.

Otherwise, an exception is logged:
```
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.
```

Note, there is `PYTHONPATH` in IIS/Azure `web.config` pointing to the app root folder which does not help:
```
 <add key="PYTHONPATH" value="D:\home\site\wwwroot" />
```

I have observed [similar issue on Python Anywhere](https://www.pythonanywhere.com/forums/topic/3730/#id_post_33244), but there it's easy to work around it by setting PA's "Working directory:" location to the app root folder.
