### ISSUE TITLE
bug in case of custom IDs

### ISSUE THREAD

**Issue by girogiro** [pyeve/eve#203]
I need to use string field 'id' instead of ObjectId field '_id' as a primary key. I added

'id': {
    'type': 'string',
    'required': True,
    'unique': True,
},

to the resource schema and set ID_FIELD = 'id' in configuration file.

Nevertheless, a POST request to create in item returns the following error:
{"issues": ["'_id'"], "status": "ERR"}

After digging in sources for a while I would say there is a bug in function find_one() in eve/io/mongo/mongo.py. First, ID_FIELD is mixed with config.ID_FIELD and also the ObjectId check should be performed only in case that primary key is '_id' or defined as objectid type in schema.

**Comment by pedro2555** [comment]
Not sure I fully understood the problem here, but I think I am experiencing this issue still.

On any project I try this, the bug is still present.

By adding ```ID_FIELD = 'id'``` to the settings.py file, basically it only seems to be used on POSTs, because the server response actually names the id field ```id```, but any other method I tried jumped back to use ```_id```.

You can do a simple test of this scenario with a POST and PATCH; PATCH will fail no matter what.
