### ISSUE TITLE
jinja2 unable to find templates.

### ISSUE THREAD

**Issue by bhanuvrat** [pyeve/eve#214]
I am trying to create some views with the same wsgi object as eve. Rendering the template with jinja2 fails with the following error:

```
jinja2.exceptions.TemplateNotFound
```

Is it against eve's design principles to use it it as a flask wsgi object and render some html pages with it? If not, how can I achieve it?

**Comment by jrc** [comment]
Try

    app = Eve(__name__)

instead of

    app = Eve()


From http://flask.pocoo.org/docs/1.0/quickstart/:
"If you are using a single module (as in this example), you should use `__name__` because depending on if it’s started as application or imported as module the name will be different ('`__main__`' versus the actual import name). This is needed so that Flask knows where to look for templates, static files, and so on."

**Comment by jrc** [comment]
The problem is that `Flask.root_path` points to Eve instead of the app source directory.

`app = Eve(__name__)` fixes the template problem but breaks Eve…

**Comment by jrc** [comment]
Hacky workaround:

    template_folder = os.path.join(os.path.dirname(__file__), 'templates')
    app = Eve(template_folder=template_folder)

**Comment by jrc** [comment]
This affects `instance_path` as well.
