### ISSUE TITLE
If-Modified-Since GET on collection returns incorrect 304 after item deletion

### ISSUE THREAD

**Issue by leth** [pyeve/eve#334]
- Have collection of more than one item
- Make request to collection index and make note of time `T`
- Delete 1 item
- Make request to collection index with `If-Modified-Since` of time `T`
- Observe resulting HTTP 304

This is very similar to Bug #243, except that the collection is not empty afterwards.

In the short term, can you suggest a way to ignore `If-Modified-Since` headers on requests to collections?

**Comment by tgm-git** [comment]
Why is this bug marked as closed?
IMS requests are still ignored on resources and while the oplog provides the foundation for several solutions, I have been unable to find any configuration options that enable it.

Are eve users expected to implement 304s on resource endpoints ourselves, if so is there a hook or callback to pass our implementation to?

While I agree that providing false positive 304s to the client is a bug, I would argue that providing false negative 304s to is also a bug.

Most of the time this is not an issue, however in my use case I have an endpoint with heavy traffic and very heavy data-load which is not cached by browsers (This is not entirely true, in some cases the data is cached, but the request is sent to backend anyway).

Could a potential solution be to retrieve all etags in the collection, hash them into a new 'resource hash' and switch to If-Match instead of IMS?

In either case I think this issue should be reopened until the bug is fixed or mediating options are available.
