### ISSUE TITLE
Not allowed role leads to a 401

### ISSUE THREAD

**Issue by touilleMan** [pyeve/eve#543]
I've notice that the authentication system in eve returns a 401 error no matter the reason.
I believe this is more a side effect of the implementation (i.e. user role is checked at the same time than it credentials).
From my understanding, a user with correct credentials but non-matching role should lead to a 403 error.

I personally fixed this in my user-defined `check_auth` function, calling `abort(403)` in case the role is not valid.
This works of course but it more a hack relying on the fact Eve is build upon Flask than a clean solution integrated in the framework.

I think it could be better to define some exceptions like `EveAuthBadCredentials` or `EveAuthBadRole` than should be raised from the user-defined `check_auth` in order to handle the 403/401 errors in the `requires_auth` decorator:

```
class EveAuthBadCredentials(Exception): pass
class EveAuthBadRole(Exception): pass

def requires_auth(endpoint_class):

    ...

            if auth and request.method not in public:
                try:
                    auth.authorized(roles, resource_name, request.method)
                except EveAuthBadCredentials:
                    return auth.authenticate(401)
                except EveAuthBadRole:
                    return auth.authenticate(403)
```

**Comment by nicolaiarocci** [comment]
Interesting, thanks. As we are approaching 0.5 release I'm scheduling this ticket for review for  next release cycle.

**Comment by nicolaiarocci** [comment]
I'm back onto this one. 

I am currently experimenting with a different pattern. 

- A new `BasicAuthEx` class is added to the featureset. It allows for finer control by supporting `is_authorized`(or `is_authenticated`) and `is_allowed` methods. 
- User is expected to at least override  `is_authorized` to provide the authentication logic (it serves the same purpose as current `BasicAuth.check_auth`) .
-  If `is_authorized` returns `False`, then a `401` is returned to the client (with proper `WWW-Authenticate` header) - the same as now
- If the previous step is successful and if `is_allowed` has been implemented, it is invoked
- If `is_allowed` returns `False`, then a  `403` is returned to the client.

This would allow the auth class to split concerns between authentication (who are you and do you have proper credentials) and authorization (are you allowed to this resource).

In order to preserve backward compatibility, `BasicAuth` would still be supported. 
Eventually I could encourage adoption of the new class in the documentation, flagging the former one as obsolete/deprecated.

Thoughts?

**Comment by rs** [comment]
Why don’t you split those two concerns in two separated classes? The authen class would be run first and if it passes, the authz would be run with the authen class instance as injected dependancy.

**Comment by nicolaiarocci** [comment]
I thought about that, but then (in the worse case scenario where you also want to check roles etc.) you would end up passing two classes to the application, which seems a bit clumsy.

**Comment by rs** [comment]
Yes you would have two classes to pass to the app. How is it an issue?

And by the way, instead of passing a class it would be better to pass an instance so we can configure it.

**Comment by johnnywell** [comment]
Besides that, it would be great if I could pass a list of auth classes, then on an auth cicle the credentials would be checked on each class until match the requirements  of one of them, then grant the access. If none matches then a proper 401 would be returned. 

This way I could accept different auth mechanics transparently, like BasicAuth for some web user actions and a HMACAuth for an mobile application.

**Comment by bthorben** [comment]
Has anything happened about his? I stumbled across the same "issue".

**Comment by bthorben** [comment]
I am using the following code as a workaround:

```
        try:
            login_name, password_hash = User.get_login_from_auth_token(token)
            user = db.query(User) \
                .filter(User.login == login_name) \
                .filter(User.password == password_hash) \
                .one()
            if not user.role in allowed_roles:
                abort(403)
        except SignatureExpired:
            return False
        except BadSignature:
            return False
        except NoResultFound:
            return False
        except Exception as e:
            raise e
```

**Comment by nicolaiarocci** [comment]
Hello folks. Have not had time to get back to this, but I still plan to.
