### ISSUE TITLE
$inc operator

### ISSUE THREAD

**Issue by ddurieux** [pyeve/eve#723]
Hello, 

I try to use "$inc" operator (http://docs.mongodb.org/manual/reference/operator/update/inc/) used to increment an integer value in mongo.

Have you a solution to use this $inc, or perhaps have you another solution to increment it?

Thanks ;)

**Comment by nicolaiarocci** [comment]
Currently, when a PATCH comes in, a `$set` is sent to mongo so you are out of luck I am afraid. You could experiment with subclassing the current mongo layer and override the `update` method to use `$inc`, or even better implement some logic to determine when to use one or the other...

In the future, an idea worth exploring might be adding support for a new endpoint setting, let's say `mongo_update_operator`, which would default to `$set` but could be switched to `$inc`. Since you can have multiple endpoints operating on the same datasource/collection, it would probably be a handy option to have.

**Comment by qb-cea** [comment]
The patch referenced above lacks proper testing, and bypasses validation for payloads that contain update operators (other than `$set`).
Can someone give me their opinion before I work on adding those?

**Comment by nicolaiarocci** [comment]
Looks good to me: go ahead with the testing, and thanks.
