### ISSUE TITLE
Cerberus 1.0 Support

### ISSUE THREAD

**Issue by nckpark** [pyeve/eve#776]
This issue is a bit premature as Cerberus 0.10 has yet to be released, but I'm curious what the plan is for updating Eve to use it? Is there any timeline in mind? I'm eager to see the impact on validation performance - it seems like there could be some significant improvements in the new code.

**Comment by nicolaiarocci** [comment]
I plan on supporting Cerberus 0.10 because it is better on all accounts. I have been hesitant however since it breaks backward compatibility in a big way so it is going to require a bit of work and, which is worse, would probably break most custom validators making the upgrade to next Eve release a pain point. 

I have not had the time to experiment with the update though, so please feel free to play with it and submit a PR if you feel like doing it.

**Comment by jim-bo** [comment]
I would like to second the request for 1.0 support. I think the advances in Cerberus 1.x would be great to have in Python-Eve. In my case the recursive schema definitions is needed.

**Comment by dkellner** [comment]
I've started playing with this. It will probably take some time, though. I am planning to post an update on this within one or two weeks.

**Comment by nicolaiarocci** [comment]
@dkellner excellent!

**Comment by dkellner** [comment]
See https://github.com/nicolaiarocci/eve/pull/917

**Comment by nicolaiarocci** [comment]
See #1001
