### ISSUE TITLE
Patch on list of objects

### ISSUE THREAD

**Issue by fteychene** [pyeve/eve#792]
Hello

For our project, we need to be able to patch a list of objects with the same behavior as a nested object.
The behavior we want to have is linked to the issue #229 but we don't want to use positional operator.

The use case we're trying to obtains is the following : 

```
"schema": {
  ...
  "categories": {
    "type": "list",
    "schema": {
      "type": "dict",
      "schema": {
        "id": {
          "type": "string",
          "required": True
        },
        "name": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      }
    }
  }
  ...
}
```

We want to be able to PATCH the resource with this type of data (No modifications wanted for the third element of the list) :

``` json
"categories": [
    {
      "name": "New name for first object in list"
    },
    {
      "id": "New id for second entry"
    },
    {
    },
    {
      "id": "New element",
      "name": "Name for new element",
      "text": "Text for new element"
    }
  ],
```

We thought to update the `resolve_nested_documents` in the patch methods to resolve the updates in the case of a object list as it's done for the nested objects.

We're currently working to implement it as a new option available as the behavior we want is not a standard one.
What do you think of this idea ?

**Comment by nicolaiarocci** [comment]
Are #1 and #2 going to replace the corresponding subdocuments in the array? Or are they going to only replace the field?

**Comment by fteychene** [comment]
In the way we want they will only replace the fields for #1 and #2.

**Comment by nicolaiarocci** [comment]
Hmm I'm unsure on this as it would be a remarkable change in PATCH behaviour. As you suggest it might be a nice feature to have *if* we also offered an option to switch this "diff edit mode" on/off... something like `DIFF_PATCH_ARRAYS` (just the first option that crossed my mind). Could be switched off by default in order to not to break backward compatibility. Thoughts?

**Comment by fteychene** [comment]
Yes sure.
It was our thought too, sorry it was not clear.
This fearture should be available only with an option and be off by default (not sure currently if it should be on ressource or request or other thing).

Another thing we think of is how could we delete an item of the list with this feature.

**Comment by txomon** [comment]
Hey! I have come with a syntax, but the problem is that it's limited to one level patches. This is, if you want to patch a document in different levels, you would have to make a patch request for each one.

Let's say we have the following document:
```
a = {
    'a': [
        {'b': {'c': [1, 2, 3, 4]}},
        {'d': {'e': [5, 6, 7, 8]}},
    ],
    'f': [
        {'g': {'h': [9, 10, 11, 12]}},
        {'i': {'j': [13, 14, 15, 16]}},
    ]
}
```

The syntax would allow to patch any level, but with some limitations. You would be overwriting anything that is not in the level of the patch. The syntax however might not be really restful, but I cannot think on another way. The only problem is the deletion should be run using PUT and specifying the rest of the items you want to maintain.

If you wanted to add a new k/v entry in the first level, that would maintain the current PATCH syntax. If you wanted to replace, say `a`s value, you would be using PUT, and if you wanted to remove `f`, you would be using a PUT, on the top level with `a` in it. Or you could be using DELETE on the key. 

If you wanted to add a new value to `a`'s array, in position 0 you would:
```
PATCH /myobjects/<id>/a/0/
{'k': {'l': [17, 18, 19, 20]}}
```

Resulting on the following document state:
```
a = {
    'a': [
        {'k': {'l': [17, 18, 19, 20]}},
        {'b': {'c': [1, 2, 3, 4]}},
        {'d': {'e': [5, 6, 7, 8]}},
    ],
    'f': [
        {'g': {'h': [9, 10, 11, 12]}},
        {'i': {'j': [13, 14, 15, 16]}},
    ]
}
```

If you wanted to replace the value for the first item, you would:
```
PUT /myobjects/<id>/a/0/
{'k': {'l': [17, 18, 19, 20]}}
```

Resulting on the following document state:
```
a = {
    'a': [
        {'k': {'l': [17, 18, 19, 20]}},
        {'d': {'e': [5, 6, 7, 8]}},
    ],
    'f': [
        {'g': {'h': [9, 10, 11, 12]}},
        {'i': {'j': [13, 14, 15, 16]}},
    ]
}
```

As I said, I don't know if this is restful or not, but the deletion of an item would be:
```
DELETE /myobjects/<id>/a/0/
```

Resulting on the following document state:
```
a = {
    'a': [
        {'d': {'e': [5, 6, 7, 8]}},
    ],
    'f': [
        {'g': {'h': [9, 10, 11, 12]}},
        {'i': {'j': [13, 14, 15, 16]}},
    ]
}
```

You would also be able to delete the first entry using a PUT, although I am not sure if this is valid syntax.
```
PUT /myobjects/<id>/a/
[{'d': {'e': [5, 6, 7, 8]}}]
```
Resulting on the same document state.

And so on and so forth. I hope this syntax resolves the problem!

**Comment by janreyho** [comment]
@nicolaiarocci  @txomon have the syntax completed?

**Comment by Leonidaz0r** [comment]
Maybe we can reduce the complexity of this problem.
Assume we want to implement a method to be able to patch the subdocuments in the original example. With embedded resources we can split this into two resources:

```
DOMAIN = {
  "outer": {
    "schema": {
      "categories": {
        "type": "list",
        "schema": {
          "type": "objectid",
          "data_relation": {
            "resource": "categories",
            "embeddable": True
          }
        }
      }
    }
  }
  "categories": {
    "schema": {
      "id": {
        "type": "string",
        "required": True
      },
      "name": {
        "type": "string"
      },
      "text": {
        "type": "string"
      }
    }
  }
}
```
Now we can change things inside categories without replacing the whole list. However to get more flexibility it would be interesting:
 * To be able to still use patch on the original resource to change a category
 * To change the list of categories without replacing all of it

The first part should be pretty easy. If eve receives a PATCH to /outer/<outer_id>/categories/<category_id>, it just has to change the URL a little bit and everything is fine. One could in addition hide the categories resource, effectively creating the originally wanted situation.

The second part is also not hard to implement. The good thing is, that now every category has a clear id field, which is known to eve(if not, we can just set ID_FIELD in the inner resource). This makes it possible to refer to an array element using that id, which makes it easy to modify the category list in an intuitive way:
POST /outer/<outer_id>/categories/
DELETE /outer/<outer_id>/categories/<category_id>
DELETE /outer/<outer_id>/categories/?where={"name": "category1"}

All these methods should be simple to implement, as they just need to call the methods for the embedded resource and update the outer list accordingly.

**Comment by Leonidaz0r** [comment]
Maybe one more note. My proposition would destroy the possibility to index into lists of arbitrary content, so it might be an alternative to not use the objectIDs to reference into the lists, but indices.
Instead of
DELETE /outer/<outer_id>/categories/<category_id>
have:
DELETE /outer/<outer_id>/categories/<category_index>

This way we can also use the same feature to remove something from a list of strings or something similar.
