### ISSUE TITLE
soft delete and auth field enable meanwhile cause deleted resource lost auth field

### ISSUE THREAD

**Issue by madawei2699** [pyeve/eve#830]
AUTH_FIELD` = '**user_id**'
SOFT_DELETE = True

schema = {
    '**user_id**':{
        'type': 'objectid',
    }
}

when soft delete and auth field enable meanwhile, database schema **_must**_ add auth field, case when eve soft delete resource and it deepcopy the resource to marked_document which dependent schema. if schema have no auth field, the marked_document also have no auth field, finally mongodb store the deleted resource which have no auth field. It make eve cannot get the deleted resource cause it enable the auth field.

**Comment by nicolaiarocci** [comment]
Hello and thanks for reporting this. Let me see if I got this right:

1. with auth field disabled you store a document
2. later on, you switch auth field on
3. at some point the document stored at 1. gest soft deleted
4. because the original document did not have any auth field, the soft deleted on also misses it
5 therefore the soft_deleted document won't be retrievable anymore by the user who deleted it.

Am I correct?

**Comment by madawei2699** [comment]
1.Enable Auth Field and store a document
2.Check mongodb and the document has auth field
3.Enable Soft Delete feature and delete the document
4.Check mongodb and the document has no auth field and have soft delete field
As you can see, the auth field is disappear. I debug the code and found when soft delete a document, in the delete function it will deepcopy the resource to marked_document which dependent the db schema(schema has no auth field explicitly cause the auth field is set in auth function), so the marked_document has lost the auth field.
To solve the problem, I add the auth field in schema explicitly.

**Comment by huiyiqun** [comment]
Same problem.

How about assign `auth_field` of `original` to `marked_document` in `methods/delete.py`?
