### ISSUE TITLE
QUESTION: DELETE on parent with data_relation

### ISSUE THREAD

**Issue by ikkaro** [pyeve/eve#907]
Hi,
I'm starting to use eve, and I'm trying to understand the best method to manage a one to many relation.

I've this schema: 

```
domains_schema = {
    'domain_name': {
        'type': 'string',
        'required': True,
        'readonly': False,
        'unique': True,
    },
}
domains = {
    'item_title': 'domains',
    'schema': domains_schema,
    'url': 'domains',

    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'domain_name'
    },
}

hostnames_schema = {
    'hostname': {
        'type': 'string',
        'required': True,
        'readonly': False,
        'unique': True,
    },
    'inuse': {
        'type': 'boolean',
        'default': True,
    },

    'domain_name' : {
        'type': 'string',
        'data_relation': {
            'resource': 'domains',
            'field':'_id',
            'embeddable': True
            },
    }
}

hostnames = {
    'item_title': 'hostnames',
    'schema': hostnames_schema,
    'url': 'hostnames',

    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'hostname'
    },

    'resource_methods': ['GET','POST',],
    'item_methods': ['GET','PATCH','DELETE'],
}
```

If I perform a DELETE in the domain resources if works fine. The requested domain item is deleted.
But all the items in the resources hostnames referencing the deleted domain persist in the database. 
I can solve this changing my schema, but I'm trying to understand how to solve relation problems in the future. How can I achieve that? 

Thanks .

**Comment by Amedeo91** [comment]
I am interesting aswell in the possibility to:
1 post a resource and having Eve to automatically recognize each embedded documents in the  body and correctly inserting it in the right collection
2 post an embedded document and having Eve to be able to automatically update the "father" document. 

Since Eve is currently not supporting it, I develop the customization myself using the hook event (aswell for a similar scenario to the one you are reporting) and adding new custom configuration to the resource level configuration (which are: father document, field in the father document when I have the link and field in document which link it to the father)

I think that we can see if Eve team would like to have it and eventually we can start to share what we did

Regards,
Amedeo
