### ISSUE TITLE
Threading in Eve

### ISSUE THREAD

**Issue by ydaniels** [pyeve/eve#953]
Hello am trying to start a thread to do a background task in eve but i never really get access to the flask app context even though i push the context , have tried different method but still the same problem

**Comment by einarhuseby** [comment]
@ydaniels here's an example using threading and running at scheduled times:

In run.py:
 ```python
if app.debug and not os.environ.get("WERKZEUG_RUN_MAIN") == "true":
    """make sure it only run once"""
    updater.start(app) # Passing the app (app = Eve(..))
```

Then in the file used for the threading look in https://github.com/FNLF/fnlf-backend/blob/develop/ext/melwin/melwin_updater.py for the logic. Note that we use a pid file since we run gunicorn in production. In `start(app)` we get seconds from `get_timer()` and pass that to `threading.Timer` then perform the task (which again will call `threading.Timer` forever). And the clue to get the correct app context is to pass the app object with `threading.Timer`  then you can use ` with app.test_request_context('api/v1/your/resource'):` in your task function.
