### ISSUE TITLE
Successful creation of invalid field which results in subsequent KeyError when querying

### ISSUE THREAD

**Issue by christabor** [pyeve/eve#977]
## Background:

I was troubleshooting some issues with my fields showing up as embedded. I am trying to simulate both 1-to-many and many-to-many relationships and have them load using the `?embedded={}` query parameters. While doing so, I found a potential issue.

## Assumptions

* I am using the default mongodb adapter, with default settings
* I have successfully used the `embedded` parameter to load a **single** reference, using the `objectid` type and `_id` field.

## Scenario

If I use this schema, there are no KeyError (but it doesn't load the embedded document either, a separate issue):

```python
resource = {
    'schema': {
        'things': {
            'type': 'list',
            'schema': {
                'type': 'integer',
                'data_relation': {
                    'resource': 'thing',
                    'field': 'some_pk',
                    'embeddable': True,
                },
            },
        }
    }
}
```

This one will *also* be successfully created (I get back a 201 when POSTing). But once I try to query it using `embedded={"things":1}`, I get a KeyError. I am aware that this is probably an invalid schema, but I imagine it should not have created it in the first place if that was the case.

```python
resource = {
    'schema': {
        'things': {
            'type': 'list',
            'data_relation': {
                'resource': 'thing',
                'field': 'some_pk',
                'embeddable': True,
            }
        }
    }
}
```

**Comment by Amedeo91** [comment]
Hi, 

for what I remember, Eve does not support automatic POST of embedded document, but I will directly add it to the collection of the resource you are doing the POST. Hence, you should customise the framework using the database hook event in order to store the field where you need and keep the reference in the main document. Personally, I do not think that Eve should automatically do the POST as there might not be the need (imagine some batch flow that adding something later on).
