### ISSUE TITLE
how to patch when query_objectid_as_string='true' on a resource

### ISSUE THREAD

**Issue by nikitph** [pyeve/eve#989]
consider this code 

`app = Eve(settings=MONGODB_SETTINGS, auth=MyBasicAuth)
# init extension
ext = EveMongoengine(app)
# register model to eve
ext.add_model(Resident)
ext.add_model(Township)
ext.add_model(Item, query_objectid_as_string='true')
ext.add_model(Message, query_objectid_as_string='true')

# let's roll
app.run(host='127.0.0.1', port=8001, debug=True)'

for item running a patch gives a 404 when i call /item/< id >

setting query_objectid_as_string='false' fixes this but i cant do that as i need that for where clauses in GET to work. a fix is to ensure _mongotize doesnt care about skip_objectid for Patch. is there a more straightforward fix anybody can suggest?

**Comment by Amedeo91** [comment]
So, if I understand right, your problem is that the query is not correctly formatted to mongodb.
To fix this, it will be enough to pass the lookup dictionary from the patch_internal to the update method and the run _mongotize.

Indeed, I think that your issue is due to the fatch that the datalayer is not correctly formatting the query. See line 464 in mongo.py
